export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const ADD_SUCCESS = "ADD_SUCCESS";
export const REMOVE_SUCCESS = "REMOVE_SUCCESS";

export const FETCH_HAIRDRESSERS = "FETCH_HAIRDRESSERS";
export const SELECT_HAIRDRESSER = "SELECT_HAIRDRESSER";

export const SET_DATE = "SET_DATE";
export const SET_TIME = "SET_TIME";

export const LIST_BOOKINGS = "LIST_BOOKINGS";
export const LIST_USER_BOOKINGS = "LIST_USER_BOOKINGS";
export const DELETE_USER_BOOKING = "DELETE_USER_BOOKING";