export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const FETCH_HAIRDRESSERS = "FETCH_HAIRDRESSERS";
export const SELECT_HAIRDRESSER = "SELECT_HAIRDRESSER";